# @name  csrf_fetch
HEAD {{sap_dev_server}}/sap/zqdrtrest/ HTTP/1.1
Authorization: Basic {{sap_dev_user}} {{sap_dev_pwd}}
X-CSRF-Token: Fetch

###

# Get Collective Value help metadata for ADRDIF_CP field POST_CODE
GET {{sap_dev_server}}/sap/zqdrtrest/entities/T/ADRDIF_CP/vhMetadata
    ?field=POST_CODE
    &fieldType=normal
    &valueHelpType=DDICSearchHelp
     
X-CSRF-Token: {{csrf_fetch.response.headers.x-csrf-Token}}
Authorization: Basic {{sap_dev_user}} {{sap_dev_pwd}}
Content-Type: application/json

###

# Get Collective Value help metadata with a single child search help for ADRCS field COUNTY
GET {{sap_dev_server}}/sap/zqdrtrest/entities/T/ADRCS/vhMetadata
    ?field=COUNTY
    &fieldType=normal
    &valueHelpType=DDICSearchHelp
     
X-CSRF-Token: {{csrf_fetch.response.headers.x-csrf-Token}}
Authorization: Basic {{sap_dev_user}} {{sap_dev_pwd}}
Content-Type: application/json

###

# Get Value help metadata for TADIR field OBJECT
GET {{sap_dev_server}}/sap/zqdrtrest/entities/T/TADIR/vhMetadata
    ?field=OBJECT
    &fieldType=normal
    &valueHelpType=DDICSearchHelp
     
X-CSRF-Token: {{csrf_fetch.response.headers.x-csrf-Token}}
Authorization: Basic {{sap_dev_user}} {{sap_dev_pwd}}
Content-Type: application/json